/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:f701519a-ccc3-4f61-ae7f-084d4aee3785",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_Y8HsZAdEx",
    "aws_user_pools_web_client_id": "3io8lmqfavkm3t9rt3oup0f22n",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "amplifyssr",
            "endpoint": "https://ocqcwp0zd5.execute-api.eu-central-1.amazonaws.com/dev",
            "region": "eu-central-1"
        }
    ],
    "aws_content_delivery_bucket": "awstest-20201018135231-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "eu-central-1",
    "aws_content_delivery_url": "https://d14ow6s9zg2mn5.cloudfront.net"
};


export default awsmobile;
